levels = {
    'easy': ['FLOWER', 'BANANA', 'APPLE', 'SPOON', 'CHEESE', 'TREE', 'OCEAN', 'SNAKE', 'BOOK', 'COOKIE', 'CAKE', 'STAR', 'HEART', 'SMILE', 'HOUSE'],
    'medium': ['COMPUTER', 'RESTAURANT', 'LIBRARY', 'PIRATE', 'BICYCLE', 'SONG', 'DOOR', 'PASSWORD', 'NATURE', 'FOREST', 'RAIN', 'MUSIC', 'PARK', 'FOOTBALL', 'GARDEN'],
    'hard': ['VODKA', 'IRONHACK', 'ZOMBIE', 'JOKER', 'WATERMELON', 'HEARTBEAT', 'DOORBELL', 'CARPET', 'WALLPAPER', 'TOOTHBRUSH', 'SEAFOOD', 'HEADACHE', 'CUPBOARD', 'PANCAKE', 'ANALYTICS']
    }
